\chapter{Motion Primitive and Invariety}
In our framework, the complex human motion is made of many motion primitive.
During motion Adaptation, neural system modifiy the basic motion primitive to synthesis new motion.
From manthematical view port, moiton primitive have many inportant features.
structural stable
a motion primitive is structural stable, structual stable mean the topololgy of a dynamic system are kept unchanged after varriou continues environment or body perturbation
The topology of dynamics system will determine some qualitative properties of motion.
controlled symetry.
motion primivitive can be modified to suit for another motion target or motion purpose, the idea of modifiy 
\chapter{Topology and Qualitative Motion Control}
In our motion control framework, we only care about the some qualitative of motion.
One key qualitative properties of motion is the final motion result,from the geometrical viewport, this mean only the
basically motion can be seperated into two group.
1 periodic motion
Some motion show pepetive pattern, from geometrical viewport, on the phaseplane, the attractor of curve form the shape of a circle.
2 discrete motion
Another idea is


\chapter{Lie Group and Quantitive Motion Control}

\section{Symmetry of Motion}
An idean in solving differential equation and mechanical control control is based on the idea of Lie Group And Simmetry.
if $x(t)$ is the solution of a differential equation $\dot{x}=F(x)$
if for a group y=G(x); if y satisfy the equation $\dot(y)=F(y)$
then y(t)=G(x(t)) is also a solution of the  the function $\dot{x}=F(x)$.
Then the group G transform the solution x(t) into another solution y(t);


For physiccally based system,
The motion of of a mechanically sistem is determined by the lagrange $L$ and corresponding Lagrange euler equation.
in our framework, the basic motion pattern is given, if we want to keep the symmetry motion, than the control problem can be simplified as an group element finding problem.
simpilifed find the corresponding group element $g$.


 
\subsection{Space Transform}


\subsection{Time Scaling}
\subsection{Motion Signature}

